# Generated by Django 3.0.6 on 2020-05-18 08:22

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtailmarkdown.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200518_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('code', wagtailmarkdown.blocks.MarkdownBlock())]),
        ),
    ]
